export const DashboardFullViewAccidentPage = 'DashboardFullViewAccidentPage';
export const SupportDocumentsPage = 'SupportDocumentsPage';
export const SupportDocumentCreditlifePage = 'SupportDocumentCreditlifePage';
export const NotificationsPage = 'NotificationsPage';
export const FavoritesPage = 'FavoritesPage';
export const PolicyDashboardPage = 'PolicyDashboardPage';
export const UserProfilePage = 'UserProfilePage';
export const TabsPage = 'TabsPage';
export const ConfirmPinPage = 'ConfirmPinPage';
export const EnterOtpPage = 'EnterOtpPage';
export const ForgotPinPage = 'ForgotPinPage';
export const LoginPage = 'LoginPage';
export const LoginPopupPage = 'LoginPopupPage';
export const WrongPinPopupPage = 'WrongPinPopupPage';
export const NewPinSuccessPage = 'NewPinSuccessPage';
export const OnboardingScreenPage = 'OnboardingScreenPage';
export const RegisterUserPage = 'RegisterUserPage';
export const RegistrationEntryPage = 'RegistrationEntryPage';
export const RegistrationSuccessfulPage = 'RegistrationSuccessfulPage';
export const SecurityQuestionsPage = 'SecurityQuestionsPage';
export const SetFingerprintPage = 'SetFingerprintPage';
export const SetPinPage = 'SetPinPage';
export const SplashScreenPage = 'SplashScreenPage';
export const TestPage = 'TestPage';
export const VerifyPhonePage = 'VerifyPhonePage';
export const ScbLaterProcessPage = 'ScbLaterProcessPage';
export const NoInternetPage = 'NoInternetPage';
export const CallSupportPage = 'CallSupportPage';
export const HomeDashboardCreditlifePage = 'HomeDashboardCreditlifePage';
export const InsuranceCardPage = 'InsuranceCardPage';
export const PolicyInfoPage = 'PolicyInfoPage';
export const SetNewpinSuccessfulLoginPage = 'SetNewpinSuccessfulLoginPage';
export const ConfirmDeleteAckPage = 'ConfirmDeleteAckPage';
export const PaymentChangeBookPage = 'PaymentChangeBookPage';
export const StoriesFullViewPage = 'StoriesFullViewPage';
export const ChallengesFullViewPage = 'ChallengesFullViewPage';
export const RewardsFullViewPage = 'RewardsFullViewPage';
export const ActivityFullViewPage = 'ActivityFullViewPage';
export const PayslipPage = 'PayslipPage';
export const ConsentPage = 'ConsentPage';
export const FaceModalPage = 'FaceModalPage';
export const FingerprintModalPage = 'FingerprintModalPage';
export const ThankYouPage = "ThankYouPage";
export const DashboardNotPage = "DashboardNotPage";
export const ScbForgotPinWarningPopupPage = "ScbForgotPinWarningPopupPage";
export const PolicyListPage = 'PolicyListPage';
export const DocumentSentConfirmationPage = 'DocumentSentConfirmationPage';
export const ModelRegisterUserWithConsentAcceptPage = 'ModelRegisterUserWithConsentAcceptPage';
export const DeviceAlreadyRegisteredPromptPage = 'DeviceAlreadyRegisteredPromptPage';
//hamburger menu

export const MenuPage = 'MenuPage';
export const AboutUsPage = 'AboutUsPage';
export const ActivityLogPage = 'ActivityLogPage';
export const ContactUsPage = 'ContactUsPage';
export const FeedbackPage = 'FeedbackPage';
export const FindLocationPage = 'FindLocationPage';
export const MyAccountPage = 'MyAccountPage';
export const PrivacyPolicyPage = 'PrivacyPolicyPage';
export const SecurityTipsPage = 'SecurityTipsPage';
export const SettingsPage = 'SettingsPage';
export const TermsAndConditionsPage = 'TermsAndConditionsPage';
export const CallMeBackPage = 'CallMeBackPage';
export const ProfileImagePage = 'ProfileImagePage';
export const NearbyLocationListPage = 'NearbyLocationListPage';
export const EditAddressPage = 'EditAddressPage';
export const EmailVerificationConfirmationPage = 'EmailVerificationConfirmationPage';
export const LogoutPromptPage = 'LogoutPromptPage';
export const EmailVerifyPromptPage = 'EmailVerifyPromptPage';
export const DetailedInteractiveTimelinePage = 'DetailedInteractiveTimelinePage';
export const TotalCoveragePage = 'TotalCoveragePage';
export const AddPolicyPage = 'AddPolicyPage';
export const HomeDashboardCreditlifeNotloginPage = 'HomeDashboardCreditlifeNotloginPage';
export const MultipleLoanPage = "MultipleLoanPage";
export const TermsAndConditionConsentPage = "TermsAndConditionConsentPage";
// Policy Loan pages
export const SingleLoanPage = "SingleLoanPage";
export const LoanSubmissionPage = 'LoanSubmissionPage';
export const AddChangeCreditCardPage = 'AddChangeCreditCardPage';
export const PolicyLoanConfirmationPage = 'PolicyLoanConfirmationPage';
export const EmailVerificationPopupPage = 'EmailVerificationPopupPage';
export const LoanTermsConditionsPage = 'LoanTermsConditionsPage';
export const DocumentPopupPage = 'DocumentPopupPage';
export const NonLoanablePolicyListPage = 'NonLoanablePolicyListPage';

//Claims pages
export const ClaimsPage = 'ClaimsPage';

// Payment page
export const PolicyLoanDashboardPage = 'PolicyLoanDashboardPage';
export const AutoDeductPaymentPage = 'AutoDeductPaymentPage';
export const StoryDetailPage = 'StoryDetailPage';
export const GlobalErrorHandlerPage = "GlobalErrorHandlerPage";
export const GenericMessagePage = "GenericMessagePage";
export const PaymentDashboardPage = "PaymentDashboardPage";
export const PaymentChangebookSuccessPage = 'PaymentChangebookSuccessPage';
export const PaymentFailAckPage = 'PaymentFailAckPage';
export const PaymentMethodPage = 'PaymentMethodPage';
export const PaymentInformationPage = 'PaymentInformationPage';
export const PaymentSucessfulRoyaltyPage = "PaymentSucessfulRoyaltyPage";
export const PromotionDetailsPage = "PromotionDetailsPage";
export const ToolTipPage = 'ToolTipPage';

//Sales
export const ConfirmationAppointmentPage = 'ConfirmationAppointmentPage';
export const ContactUsProductPage = 'ContactUsProductPage';
export const ProductDetailPage = 'ProductDetailPage';
export const ProductDetailMorePage = 'ProductDetailMorePage';
export const ServiceFailPage = 'ServiceFailPage';
export const SessionTimeOutPage = 'SessionTimeoutPage';
export const DiffUserFailPage = 'DiffUserFailPage'
export const NoMobileModalPage='NoMobileModalPage'
export const NoDocumentDownloadPage='NoDocumentDownloadPage';